MIC 2705 | Network Layer
TinkoffCreditSystems/AcquiringSdk_IOS pull request #41
Opened 2021-02-04 14:40 UTC by grishamsc

Сетевой слой с покрытием тестами основных компонентов.

Интерфейсы основных компонентов:
`NetworkClient`
`URLRequestPerformer`
`NetworkClientRequestBuilder`
`HTTPURLResponseValidator`
`NetworkRequestAdapter`

Дефолтные реализации:
`DefaultNetworkClient`
`DefaultNetworkClientRequestBuilder`
`DefaultHTTPURLResponseValidator`
в качестве дефолтного `URLRequestPerformer` используется `URLSession`

Тесты для:
`DefaultNetworkClientRequestBuilder`
`DefaultHTTPURLResponseValidator`
`DefaultNetworkClient `
и есть "интеграционные" для `DefaultNetworkClient`, где подменяется только `URLRequestPerformer`.

![Untitled Diagram](https://user-images.githubusercontent.com/2726726/106907503-5f8a4680-670f-11eb-90bc-a3d8adc913bc.jpg)

2021-02-26 15:47 UTC, d-kv requested changes

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore.podspec
>  	spec.resource = "TinkoffASDKCore/TinkoffASDKCore/**/*.{lproj,strings}"
не совсем к сетевом слою, конечно, но лучше юзать resource_bundle

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/Network/Implementations/DefaultNetworkClient.swift
> +                    // TODO: Handle this case
?

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/Network/Implementations/DefaultNetworkClientRequestBuilder.swift
> +        case .url: fatalError("TODO: URLEncoding")
?

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        let task: URLSessionDataTask = session.dataTask(with: request) { data, response, networkError in
возможно, стоит взять другое название для методов протокола, чтобы не было пересечений в названиях

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/Network/DefaultNetworkClientRequestBuilderTests.swift
> +        do {
можно тест сделать throws и не париться

2021-02-26 15:47 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/Network/DefaultNetworkClientRequestBuilderTests.swift
> +            XCTAssertNotNil(urlRequest.httpBody, "urlRequest's httpBody can't be nil")
я бы сделал одну точку отказа у теста, эта проверка выглядит лишней

2021-02-26 16:02 UTC, grishamsc commented on TinkoffASDKCore.podspec
>  	spec.resource = "TinkoffASDKCore/TinkoffASDKCore/**/*.{lproj,strings}"
да, планирую это сделать, но не в самое ближайшее время

2021-02-26 16:03 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/Network/Implementations/DefaultNetworkClientRequestBuilder.swift
> +        case .url: fatalError("TODO: URLEncoding")
на это у меня есть отдельная задача

2021-02-26 16:03 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        let task: URLSessionDataTask = session.dataTask(with: request) { data, response, networkError in
соглашусь

2021-02-26 16:04 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/Network/DefaultNetworkClientRequestBuilderTests.swift
> +            XCTAssertNotNil(urlRequest.httpBody, "urlRequest's httpBody can't be nil")
да, повыпилываю лишние ассерты

2021-02-27 09:43 UTC, grishamsc commented on TinkoffASDKCore.podspec
>  	spec.resource = "TinkoffASDKCore/TinkoffASDKCore/**/*.{lproj,strings}"
создал у нас задачку

2021-02-27 10:25 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/Network/DefaultNetworkClientRequestBuilderTests.swift
> +            XCTAssertNotNil(urlRequest.httpBody, "urlRequest's httpBody can't be nil")
поубирал

2021-02-27 10:25 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/Network/DefaultNetworkClientRequestBuilderTests.swift
> +        do {
✅

2021-02-27 10:28 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        let task: URLSessionDataTask = session.dataTask(with: request) { data, response, networkError in
✅

2021-02-27 10:29 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/Network/Implementations/DefaultNetworkClient.swift
> +                    // TODO: Handle this case
убрал

2021-03-02 07:56 UTC, d-kv approved these changes

2021-03-03 09:23 UTC, merged