MIC 2868 | Localization
TinkoffCreditSystems/AcquiringSdk_IOS pull request #46
Opened 2021-02-25 14:31 UTC by grishamsc

2021-02-26 15:52 UTC, d-kv requested changes

2021-02-26 15:52 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/Localization/Localization.swift
> +private final class BundleProvider {
этот файл автогенерируемый или нет?

2021-02-26 15:52 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/ru.lproj/Localizable.strings
> +"NetworkError.emptyBody" = "Пустое тело в ответе";
Я бы написал "Пустой ответ", хотя с русским у меня не очень

2021-02-26 15:52 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/en.lproj/Localizable.strings
> +"NetworkError.transportError" = "Transport error";
Нужно ли хранить локализацию в Core? Я сторонник того, что строки локализации насаживаются в UI. Т.е. core слой возвращает код ошибки, а уже UI решает, какой выбрать текст.

2021-02-27 10:39 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/Localization/Localization.swift
> +private final class BundleProvider {
не

2021-02-27 10:40 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/ru.lproj/Localizable.strings
> +"NetworkError.emptyBody" = "Пустое тело в ответе";
кажется, что лучше, чем у меня :)

2021-02-27 10:47 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/en.lproj/Localizable.strings
> +"NetworkError.transportError" = "Transport error";
можно обсудить, но тут какая история
Core не обязательно используется вместе с UI, клиент вполне себе может подключить только Core, если ему нужны только вызовы в API делать. и получается два момента:
- ошибки из АПИ отдают локализованные строки, которые логично отдавать через errorDescription и получится, как мне кажется, не очень, что часть ошибок из СДК можно спокойно отобразить, а часть будет без какого-то осмысленного текста
- клиенту-пользователю Core придется ковыряться в ошибках, определяя, что же конкретно эта за ошибка

пока писал пришла мысль давать возможность клиенту передавать что-то под интерфейсом типа `ErrorLocalizationProvider` и брать оттуда. можно поставить как задачу на попозже

2021-03-01 10:12 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/en.lproj/Localizable.strings
> +"NetworkError.transportError" = "Transport error";
ok

2021-03-02 07:58 UTC, d-kv approved these changes

2021-03-03 09:23 UTC, merged