MIC 2867 | API Layer Tests
TinkoffCreditSystems/AcquiringSdk_IOS pull request #47
Opened 2021-02-25 14:37 UTC by grishamsc

2021-02-26 13:19 UTC, d-kv requested changes

2021-02-26 13:19 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringTokenBuilderTests.swift
> +        let expectedToken = expectedTokenString.sha256()
Я бы упростил до `let expectedToken = password.sha256()`

2021-02-26 13:19 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringTokenBuilderTests.swift
> +    let password = "password"
В качестве тестовых данных неплохо юзать рандомные данные, Fakery неплохо справляется с этой темой. (Просто на будущее, сейчас не надо фиксить).

2021-02-26 13:19 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +            }
можно использовать 2 элемента, чтобы функция помещалась на экран

2021-02-26 13:19 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/APIURLBuilderTests.swift
> +            _ = try apiUrlBuilder.buildURL(host: host)
XCTAssertThrows?

2021-02-26 13:19 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +                let _ = try result.get()
тоже можно XCTAssertThrows

2021-02-26 14:12 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +            do {
да, работает, т.к. под капотом у `api` моковый `networkClient`, который сразу вызывает `completion` с заданными данными
но, пожалуй, имеет смысл добавить Expectation, что бы, если там, о чем выше написал, что-то изменится, не ломалось ничего 👌

2021-02-26 14:15 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +extension AcquiringAPIIntegrationTests {
почему в extension? идея была в том, что метод, который в нем, не является непосредственно "исполняемым" тестом, а его вызывают двое других "исполняемых", но сейчас видится, что совершено бессмысленная штука

2021-02-26 14:17 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringTokenBuilderTests.swift
> +        let expectedToken = expectedTokenString.sha256()
да, окей. изначально сделал так для единообразия с другими тестами

2021-02-26 14:18 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +            }
увлекся :)

2021-02-26 14:58 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringTokenBuilderTests.swift
> +    let password = "password"
да, имеет смысл закинуть задачу на перспективу

2021-02-26 15:08 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/APIURLBuilderTests.swift
> +            _ = try apiUrlBuilder.buildURL(host: host)
через do catch удобнее проверять конкретный тип ошибки :)

2021-02-26 15:08 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +                let _ = try result.get()
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/47#discussion_r583705093

2021-02-26 15:16 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
> +            apiRequestExpectation.fulfill()
при добавлении expectation надо ещё добавить `waitForExpectations(timeout: 5)`

2021-02-26 15:16 UTC, d-kv approved these changes

2021-03-02 07:58 UTC, d-kv approved these changes

2021-03-03 09:23 UTC, merged