MIC 2823(part2) | API Layer integration
TinkoffCreditSystems/AcquiringSdk_IOS pull request #49
Opened 2021-03-02 16:43 UTC by grishamsc

Check3DSVersionRequest
GetPaymentStateRequest
ChargePaymentRequest
GetCardListRequest
AddCardRequest
AttachCardRequest

2021-03-05 15:10 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/AttachCardRequest.swift
> +        if let encryptedCardData = try? encryptor.encrypt(string: formattedCardData, publicKey: publicKey) {
ошибочку не надо залогировать?

2021-03-05 15:15 UTC, d-kv requested changes

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/ChargePaymentRequest.swift
> +        return (try? paymentChargeRequestData.encode2JSONObject(dateEncodingStrategy: .iso8601)) ?? [:]
ошибочку не надо залогировать?

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetPaymentStateRequest.swift
> +        return (try? paymentInfoData.encode2JSONObject()) ?? [:]
аналогично

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
не хватает описания метода

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
не хватает описания метода

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
не хватает описания метода

2021-03-05 15:15 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    public func addCardInit(data: InitAddCardData,
Не пойму, зачем суффикс Init. Вроде как просто добавление карты происходит.

2021-03-07 19:02 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/AttachCardRequest.swift
> +        if let encryptedCardData = try? encryptor.encrypt(string: formattedCardData, publicKey: publicKey) {
там и в других местах есть штуки которые хорошо бы логгировать. давай помечу этих вещи чем-то типа ``TODO: Log error`` и потом пройдусь и все сразу залоггирую
создал себе отдельную задачу на это

2021-03-07 19:02 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/ChargePaymentRequest.swift
> +        return (try? paymentChargeRequestData.encode2JSONObject(dateEncodingStrategy: .iso8601)) ?? [:]
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/49#discussion_r589072735

2021-03-07 19:02 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetPaymentStateRequest.swift
> +        return (try? paymentInfoData.encode2JSONObject()) ?? [:]
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/49#discussion_r589072735

2021-03-07 19:26 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    public func addCardInit(data: InitAddCardData,
это наследие) мне тоже немного глаз режет, но хотелось поменьше всего публичного менять
но, как уже отписал в другом реквесте, кажется, что уже ничего страшного нет, т.к. много другого пришлось переименовать :)

2021-03-07 19:28 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    public func addCardInit(data: InitAddCardData,
ну и идея, насколько я понимаю, была в том, что т.к. добавления карты дергается два метода `AddCard`, а затем `AttachCard`, то эти два этапа обозначить как InitAdd и FinishAdd

2021-03-07 19:30 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
✅

2021-03-07 19:30 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
✅

2021-03-07 19:30 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    ///
✅

2021-03-09 10:23 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Requests/AttachCardRequest.swift
> +        if let encryptedCardData = try? encryptor.encrypt(string: formattedCardData, publicKey: publicKey) {
ок

2021-03-09 10:25 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift
> +    public func addCardInit(data: InitAddCardData,
понял, ок

2021-03-09 13:31 UTC, merged