MIC 2825
TinkoffCreditSystems/AcquiringSdk_IOS pull request #52
Opened 2021-03-04 15:50 UTC by grishamsc

- extract IPAddressProvider from Utils to separate file
- transform IPAddressProvider to struct
- inject IPAddressFactory to IPAddressProvider
- return from AcquiringSDK IPAddress instead String

2021-03-04 16:04 UTC, Dimat112 approved these changes

2021-03-05 15:22 UTC, d-kv requested changes

2021-03-05 15:22 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/IP/IPAddress.swift
> +public protocol IPAddress {
нет доки

2021-03-05 15:22 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/IP/IPAddressProvider.swift
> +public struct IPAddressProvider {
нет доки

2021-03-05 15:22 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        return nil
непонятно

2021-03-05 15:29 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        return nil
в след ПР NetworkTransport ушел в небытие :)

2021-03-05 15:29 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/IP/IPAddress.swift
> +public protocol IPAddress {
принято

2021-03-05 15:29 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/IP/IPAddressProvider.swift
> +public struct IPAddressProvider {
принято

2021-03-09 10:12 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/IP/IPAddress.swift
> +public protocol IPAddress {
✅

2021-03-09 10:26 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
> +        return nil
ок

2021-03-09 10:26 UTC, d-kv approved these changes

2021-03-09 13:32 UTC, merged