MIC 2831(part1) | Payment logic — Cards
TinkoffCreditSystems/AcquiringSdk_IOS pull request #54
Opened 2021-03-09 20:10 UTC by grishamsc

2021-03-10 17:43 UTC, cheshiregit commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +        assembly = UIAssembly()
Можно убрать строчку раз уж и так внутри инициализируем

2021-03-10 17:46 UTC, cheshiregit commented on TinkoffASDKUI/TinkoffASDKUI/Payments/PaymentController.swift
> +/// Объект, предоставляющие для `PaymentController` UI-компоненты для совершения платежа
опечатка

2021-03-10 18:09 UTC, cheshiregit commented on TinkoffASDKUI/TinkoffASDKUI/Misc/Atomic.swift
> +        lock.lock()
А вот при чтении наверное могли бы обойтись без lock

2021-03-10 18:09 UTC, cheshiregit approved these changes

2021-03-10 19:48 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +        assembly = UIAssembly()
хотя наверное лучше сразу это и сделать

2021-03-10 20:21 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Misc/Atomic.swift
> +        lock.lock()
не, у нас же в таком случае чтение никак не будет защищено в процессе записи и можно будет считать данные в момент чтения. представь, если запись занимает долгое время. гипотетический пример - мы в процессе записи в цикле от 0 до 100000 на каждой итерации кладем счетчик цикла в массив. в таком случае, если обратиться в процессе записи к массиву, то чтение произойдет, когда цикл еще не закончился и мы в ответе получим обрезанный массив.

или если более низкоуровнево визуализировать - запись или чтение для процессора это не одна команда, а несколько, допустим по 5 на каждую операцию. и у нас гарантии, что выполняя запись на одном потоке, процессор посреди этого, выполнив только 2 команды для чтения, не даст процессорное время для потока, который начнет читать. 
и защитив только запись локом, мы обезопасимся от кейса, когда с двух разных потоков будет происходить запись, процессор не сможет переключиться на вторую запись, пока первая не закончится. а вот на чтение сможет легко, ему ничего не помешает

но может имеет смысл вместо просто NSLock реализовать ReadWriteLock

2021-03-11 08:34 UTC, cheshiregit commented on TinkoffASDKUI/TinkoffASDKUI/Misc/Atomic.swift
> +        lock.lock()
Да, есть такое. Кейс с изменением счетчика в цикле достаточно специфичный, но действительно рано или поздно может случиться ситуация, когда мы при чтении получим невалидные данные
Я вспомнил реализацию счетчика с помощью параллельной очереди и барьера, что позволяет нам одновременно читать, при этом блокируется чтение при записи. 
С `NSLock` действительно лучше все же блокировать чтение, чтобы потом не выстрелить себе в ногу

2021-03-11 08:46 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Misc/Atomic.swift
> +        lock.lock()
кейс с циклом надуманный конечно, я его для демонстрации привел, мне лично так легче воспринимать и понимать :) 
параллельная очередь и барьер это как раз вариация ReadWriteLock, в таком кейсе ты по сути так же блокируешь чтение, как с оборачиванием в `lock`/`unlock`,  только это происходит не так явно, а засчет барьерной таски на запись и собственно только в момент, когда запись происходит. и ты прав, тут преимущество получается засчет того, что читать можно сколько угодно параллельно, а не серийно, как в случае с `NSLock`, но с другой стороны, решение `NSLock` само по себе работает быстрее, чем решение с очередями

2021-03-11 11:31 UTC, d-kv requested changes

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/3DS/ThreeDSDeviceParamsProvider.swift
> +struct DefaultThreeDSDeviceParamsProvider: ThreeDSDeviceParamsProvider {
3ds-ка скопирована из нашей коры?

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/3DS/ThreeDSURLRequestBuilder.swift
> +                        APIConstants.Keys.messageVersion: version ?? "",
выглядит подозрительно, тут бага не будет?

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Models/PaymentId.swift
> +public typealias PaymentId = Int64
Точно инт? Может строку?

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/Models/PaymentSourceData.swift
>      ///   - rebuidId: идентификатор родительского платежа
rebillId

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/Check3DSRequestData.swift
> +    public let paymentId: Int64
PaymentId?

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentInfoData.swift
>      var paymentId: Int64
same

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUI/Payments/CardPayment.swift
> +final class CardPayment: Payment {
Может назвать этот класс координатором? Текущее название сбивает с толку. И наследование от Payment тоже непонятно.

2021-03-11 11:31 UTC, d-kv commented on TinkoffASDKUI/TinkoffASDKUI/Payments/PaymentController.swift
> +            payment.start()
ну рили координатор

2021-03-11 11:47 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/3DS/ThreeDSDeviceParamsProvider.swift
> +struct DefaultThreeDSDeviceParamsProvider: ThreeDSDeviceParamsProvider {
нет, реализацию, которая уже тут была, чуть облагородил

2021-03-11 11:59 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/Models/PaymentId.swift
> +public typealias PaymentId = Int64
да, надо уже поменять на строку, как обсуждали. в этом ПР и сделаю

2021-03-11 12:00 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/Models/PaymentSourceData.swift
>      ///   - rebuidId: идентификатор родительского платежа
в след ПР уже будет исправлено, уже заметил :D

2021-03-11 12:00 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/Check3DSRequestData.swift
> +    public let paymentId: Int64
- [ ] поменять тип

2021-03-11 12:01 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentInfoData.swift
>      var paymentId: Int64
- [ ] поменять тип

2021-03-11 13:45 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Payments/PaymentController.swift
> +/// Объект, предоставляющие для `PaymentController` UI-компоненты для совершения платежа
- [ ]

2021-03-11 13:46 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
> +        assembly = UIAssembly()
✅

2021-03-11 13:51 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/3DS/ThreeDSURLRequestBuilder.swift
> +                        APIConstants.Keys.messageVersion: version ?? "",
соглашусь. убрал возможность опциональности и вынес обработку этого момента на самый высокий уровень в `CardPaymentProcess` и оставил тудуху, что бы логировать

2021-03-11 13:54 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/Check3DSRequestData.swift
> +    public let paymentId: Int64
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/56

2021-03-11 13:54 UTC, grishamsc commented on TinkoffASDKCore/TinkoffASDKCore/API/RequestData/PaymentInfoData.swift
>      var paymentId: Int64
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/pull/56

2021-03-11 13:55 UTC, grishamsc commented on TinkoffASDKUI/TinkoffASDKUI/Payments/CardPayment.swift
> +final class CardPayment: Payment {
переименовал в `PaymentProcess`

2021-03-11 14:00 UTC, d-kv approved these changes

2021-03-11 17:36 UTC, merged